import { ShopId } from '../types/shop.js';
export const SHOPS = {
    [ShopId.RAJ_FRUITS_AND_VEGETABLES]: {
        id: ShopId.RAJ_FRUITS_AND_VEGETABLES,
        code: 'RAJ',
        name: 'RAJ FRUITS AND VEGETABLES',
        shortName: 'RAJ Fruits',
        tagline: 'Wholesale Fruits & Vegetable Merchant',
        primaryColor: '#166534',
        badgeBg: 'bg-emerald-100 text-emerald-800 border-emerald-300',
        ownerName: 'Rajesh Raju',
        logoUrl: null,
        mobileNumber: '9845000001',
        alternateNumber: '08023456781',
        email: 'raj.fruits@rajuvegetables.com',
        address: 'Shop No. 12, APMC Market Yard, Yeshwanthpur',
        city: 'Bengaluru',
        state: 'Karnataka',
        pincode: '560022',
        description: 'Premium wholesale vendor for fresh farm-grown vegetables and local fruits.',
        invoicePrefix: 'RAJ',
        receiptPrefix: 'RAJR',
        defaultLanguage: 'en',
        currency: 'INR',
        status: 'active',
        createdAt: '2026-01-01T00:00:00.000Z',
        themeColor: 'green',
        notificationPreferences: { email: true, sms: true, whatsapp: false },
        backupPreferences: { daily: true, retentionDays: 30 }
    },
    [ShopId.G_R_FRUITS_AND_VEGETABLES]: {
        id: ShopId.G_R_FRUITS_AND_VEGETABLES,
        code: 'GR',
        name: 'G R FRUITS AND VEGETABLES',
        shortName: 'G R Fruits',
        tagline: 'Commission Agent & Wholesale Merchant',
        primaryColor: '#1d4ed8',
        badgeBg: 'bg-blue-100 text-blue-800 border-blue-300',
        ownerName: 'G. Ramachandra',
        logoUrl: null,
        mobileNumber: '9845000002',
        alternateNumber: '08023456782',
        email: 'gr.fruits@rajuvegetables.com',
        address: 'Shop No. 15, APMC Market Yard, Yeshwanthpur',
        city: 'Bengaluru',
        state: 'Karnataka',
        pincode: '560022',
        description: 'APMC Commission Agent supplying root vegetables and fresh leaves in bulk.',
        invoicePrefix: 'GR',
        receiptPrefix: 'GRR',
        defaultLanguage: 'en',
        currency: 'INR',
        status: 'active',
        createdAt: '2026-01-01T00:00:00.000Z',
        themeColor: 'blue',
        notificationPreferences: { email: true, sms: false, whatsapp: true },
        backupPreferences: { daily: true, retentionDays: 14 }
    },
    [ShopId.PRIYAKRISHNA_FRUITS_AND_VEGETABLES]: {
        id: ShopId.PRIYAKRISHNA_FRUITS_AND_VEGETABLES,
        code: 'PK',
        name: 'PRIYAKRISHNA FRUITS AND VEGETABLES',
        shortName: 'Priyakrishna',
        tagline: 'Wholesale Vegetable Supplier & Distributor',
        primaryColor: '#ea580c',
        badgeBg: 'bg-orange-100 text-orange-800 border-orange-300',
        ownerName: 'Krishna Kumar',
        logoUrl: null,
        mobileNumber: '9845000003',
        alternateNumber: '08023456783',
        email: 'priyakrishna@rajuvegetables.com',
        address: 'Shop No. 18, APMC Market Yard, Yeshwanthpur',
        city: 'Bengaluru',
        state: 'Karnataka',
        pincode: '560022',
        description: 'Specialized distribution partner for high-yield vegetables, potatoes, and onions.',
        invoicePrefix: 'PK',
        receiptPrefix: 'PKR',
        defaultLanguage: 'kn',
        currency: 'INR',
        status: 'active',
        createdAt: '2026-01-01T00:00:00.000Z',
        themeColor: 'orange',
        notificationPreferences: { email: false, sms: true, whatsapp: true },
        backupPreferences: { daily: false, retentionDays: 7 }
    },
};
export const ALL_SHOPS = Object.values(SHOPS);
