export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  CUSTOMERS: '/customers',
  PRODUCTS: '/products',
  BILLING: '/billing',
  ORDERS: '/orders',
  PAYMENTS: '/payments',
  RECEIPTS: '/receipts',
  LEDGER: '/ledger',
  REPORTS: '/reports',
  HISTORY: '/history',
  PENDING: '/pending',
  PARTIAL: '/partial',
  CLEARED: '/cleared',
  BACKUP: '/backup',
  SETTINGS: '/settings',
  PROFILE: '/profile',
  UNAUTHORIZED: '/unauthorized',
  FORBIDDEN: '/forbidden',
} as const;
